### ISSUE TITLE
Integrate the new library with <Image>

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#111]
Requires https://github.com/frontity/frontity/issues/72 and https://github.com/frontity/frontity/issues/73

Child of https://github.com/frontity/frontity/issues/71

**Comment by orballo** [comment]
The `threshold` value should be different for horizontal and vertical offsets.

**Comment by orballo** [comment]
Waiting for a new release of `vanilla-lazyload` with support for string values for `threshold` setting.
