### ISSUE TITLE
Error: no content rendered on Post

### ISSUE THREAD

**Issue by orballo** [frontity/saturn-theme#126]
Link: https://preamp.wp-pwa.com/?siteId=FNZLCxnLCsqWkk3FL&type=post&id=10561&dev=true&static=https%3A%2F%2Fpreamp.wp-pwa.com%2F&env=prod&perPage=10&device=mobile&initialUrl=https%3A%2F%2Fdecoracionyjardines.com%2Fconsejos-almacenar-mobiliario-del-jardin-invierno

**Comment by DAreRodz** [comment]
This problem is caused by the REST API of a particular client and it will be solved when that API has been fixed.
