### ISSUE TITLE
Error when loading a page in List view

### ISSUE THREAD

**Issue by orballo** [frontity/saturn-theme#128]
Steps to reproduce:

1. Go to https://ayudaparamanualidades.com/?pwa=true
2. Click on **PUBLICA TUS PROPIAS MANUALIDADES** in the nav bar.

![Screen Shot 2018-08-27 at 10.31.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6202d4f976d5001232e9d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f46b7191a379ef0c2850415d46be5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5df54ee94a56a1173164f43b.png)

**Comment by luisherranz** [comment]
Don't seem to be solved yet.

**Comment by luisherranz** [comment]
It was a problem with the deploy. Closed now.
