### ISSUE TITLE
AMP Error: Invalid URL protocol '¨https:' for attribute 'href' in tag 'a'

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/saturn-theme#131]
All posts of https://estasdemoda.com are showing this AMP error: Invalid URL protocol '¨https:' for attribute 'href' in tag 'a'.

Links:

- https://amp.estasdemoda.com/fotografia-de-moda/?siteId=NJ44fuPkXh3a2Fx7Y&env=prod&dev=true&singleType=post&singleId=56967&initialUrl=https://estasdemoda.com/fotografia-de-moda/

- https://validator.ampproject.org/#url=https%3A%2F%2Famp.estasdemoda.com%2Ffotografia-de-moda%2F%3FsiteId%3DNJ44fuPkXh3a2Fx7Y%26env%3Dprod%26dev%3Dtrue%26singleType%3Dpost%26singleId%3D56967%26initialUrl%3Dhttps%3A%2F%2Festasdemoda.com%2Ffotografia-de-moda%2F&env=prod&dev=true&singleType=post&singleId=56967&initialUrl=https%3A%2F%2Festasdemoda.com%2Ffotografia-de-moda%2F

**Comment by orballo** [comment]
Original HTML is not valid. @reyes Customer should be informed.
