### ISSUE TITLE
Content bug in post view

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/saturn-theme#153]
The content of the following post is not showing up properly in the PWA.

Link: https://arquitecturaideal.com/alfombras-gan-para-crear-espacios-acogedores/

![Post-in-PWA.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e3c98213b6b5001a7ac226/125516c66e82c728ace21e0d46d89b8937cf8aa7c2d98862e611b2843b492d762a10e17132d0e17cec112f565e5b4eff425d5c44fcfb8f79f5b26d25de4e17ff933c0120996048e6edc00db513bb27814e80b5b48e4bc4ef3f27e3888b5d73.png)

**Comment by luisherranz** [comment]
I'm going to take a look

**Comment by luisherranz** [comment]
Closed in favor of https://github.com/frontity/wp-plugin/issues/29.
