### ISSUE TITLE
[50] Gdpr warning margin problem in iOS

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#157]
It looks like the GDPR warning appears with a wrong right margin in Safari 9. I don't know if it affects iOS 10, 11 and 12, but if it doesn't **we won't fix it**, as it wouldn't be really important.

![Screen Shot 2018-10-08 at 09.30.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454fb6b7191a378e60c2851415a4cbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb50ff42e84d5ca11b3162f43b.png)

Size: **all sites (2M)**
Environment: **production (x5)**
Range: **high (x5)**
Behaviour: **not-nice (x1)**
Mass: **marginal (x1)**
PRIORITY: **[50]**

**Comment by luisherranz** [comment]
I've just checked in iOS 11 and doesn't seem to be happening. Next step would be to check in iOS 10.

**Comment by DAreRodz** [comment]
Closing as not reproducible.
