### ISSUE TITLE
[5.25] iVoox iframe totally breaks the PWA

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#161]
When accessing this post https://thewing.es/the-wing-nba-podcast-2k19-rafatgr/ the PWA breaks, the screen becomes white an unusable. 

**Size:** `0.01`
**Environment:** `5`
**Range:** `1`
**Behaviour:** `5`
**Mass:** `5`

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ebtu)

**Comment by DAreRodz** [comment]
iVoox iframes are working in `dev` branch. Posts with those iframes don't break the PWA anymore.
