### ISSUE TITLE
Use data-src for images if it exists in content

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/saturn-theme#171]
Some WP may have lazy load plugins installed with the correct `src` in `data-src`, like this:
```html
<img data-expand="600" class="lazyload aligncenter wp-image-8578 size-full" src="https://mediamaklumat.com/wp-content/plugins/media-ace/includes/lazy-load/images/blank.png" data-src="https://mediamaklumat.com/wp-content/uploads/2018/10/cara-buat-nasi-lemak.jpg"
```
so we should use `data-src` if it is present.

First demo affected by this issue:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A9

Second demo affected by this issue:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A10

**Comment by orballo** [comment]
The plugin part will be developed later in https://github.com/frontity/wp-plugin/issues/45 because is not relevant to demos and therefore not urgent.
