### ISSUE TITLE
Don't show placeholder when there is no image in a post

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/saturn-theme#173]
If a featured imaged is not set in a post, and there is no image in the content, don't show the placeholder at the top of the page and at the list of posts.

Example of a lists of posts with some posts without image (At "TECNOLOGÍA" category):
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A6

Example of post without image:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A7

**Comment by SantosGuillamot** [comment]
I am not sure if it is related to this issue https://github.com/frontity/wp-org-connection/issues/8

**Comment by luisherranz** [comment]
We can check if `entity.media.featured.id === null`.

**Comment by luisherranz** [comment]
For some reason, saturn is not using the same code when the theme is configured not to show a featured image:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A12
than when featured image is missing:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A13

Besides, in the second case, the author and date are hidden by the menu bar:
![Screen Shot 2018-10-31 at 11.44.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379ee0c2f55415e4bbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc58ff43e34a56a4153e6af43b.png)
