### ISSUE TITLE
[75] Users should be able to see posts with galleries with more than 200 images

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#184]
When galleries have more than 100 images, the request to the database fails. Actually, it may fail with 100 images too, due to a server timeout.

We should investigate first which is a good maximum number of images for large databases, then we should retrieve images in batches when galleries have more than that.

Affected urls:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A23

----

Pageviews: **(0.1M)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[75]**

**Comment by SantosGuillamot** [comment]
#notify
