### ISSUE TITLE
[450] Scroll position changes when going back from an image

### ISSUE THREAD

**Issue by DAreRodz** [frontity/saturn-theme#189]
If you go back from an image context, the previous scroll position is not restored properly. It is happening in all blogs.

How to reproduce:

1. Go to a blog homepage.
2. Click on the first post.
3. Scroll down to the next post.
4. Click on the first image (featured or content media).
5. Click on the 'close' button or 'go back' button.

----

Pageviews: **(3)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[450]**

**Comment by DAreRodz** [comment]
It may be related to the 'sameHeight' component.

**Comment by luisherranz** [comment]
@DAreRodz forgot to assign a size?

**Comment by DAreRodz** [comment]
@luisherranz I was waiting for the daily meeting  😊

**Comment by luisherranz** [comment]
I've taken a look at the last meeting notes and it looks we settled on this _"First size should be given by the supporter or the bug opener"_ but we can discuss it later.
