### ISSUE TITLE
Theme footer shows "powered by Worona"

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#20]
child of https://github.com/wp-pwa/saturn-theme/issues/48

**Comment by luisherranz** [comment]
@Poliuk could you please give us a bigger (or SVG) image for Sirv?

**Comment by Poliuk** [comment]
@luisherranz @orballo Here you have a SVG version: https://drive.google.com/open?id=1sGUJDggwZxQ5mg8yo718s8Zfvmv1FwOR

Let me know if it works :)

**Comment by orballo** [comment]
@Poliuk perfect, thanks :)

**Comment by Poliuk** [comment]
@orballo sure! Can you define "big"? Haha give me exact dimensions!

**Comment by orballo** [comment]
@Poliuk Don't know, maybe `600px` width? We should be able to crop it for different screen densities. The current logo is `100px` width and I think the biggest we use is x3 or `300px`. With `600px` we should be good.

**Comment by luisherranz** [comment]
You don't need to use png, you can convert text to vectors before exporting the svg.

**Comment by Poliuk** [comment]
@orballo can you try with this one? It's an svg without font. https://drive.google.com/open?id=1WEyh8j4Mwx_osCN2bvSUZ_Nd12NdQ1Kz
