### ISSUE TITLE
[450] Scroll jumps on swipe

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#203]
It looks like if you scroll down a post and swipe, sometimes the scroll jumps to the middle of the screen.

Like this:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A39

@orballo i'm testing mentions when editing issue descriptions.

----

Pageviews: **(3)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[450]**

**Comment by luisherranz** [comment]
I thought it may be related to dynamic height ads, but it's not. It also happens in other blogs:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A40

**Comment by DAreRodz** [comment]
I'm not sure why, but it seems like this issue was already resolved in [this PR](https://github.com/frontity/frontity/pull/159).

**Comment by DAreRodz** [comment]
There was a problem with the deploy alias when I tested the PR in pre-production,  that's why I thought it was not solved yet.

Closing the issue.

**Comment by luisherranz** [comment]
💪
