### ISSUE TITLE
[27] Post images are not showing

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/saturn-theme#211]
Relevant url:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A45

The images have a WP class `wp-image-{id}` but they don't exist in the db, and at the same time the `src` is external. We should check in the `image` processor that when we are using an `id` the `src` belongs to the blog, and if it's external, we skip the `id` and go for the image to the original `src`. 

----
#cs: @SantosGuillamot 
#supporter: @DAreRodz 

https://frontity.pipedrive.com/deal/427
Pageviews: **(0.01)**
Environment: **integration is finishing (x6)**
Range: **medium (x3)**
Behaviour: **no frontity without it (x10)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[27]**

**Comment by DAreRodz** [comment]
Our plugin should not add `data-attachment-id` attribute if the `wp-image-{id}` is present but the `src` attribute points to another site.

**Comment by orballo** [comment]
This should be fixed in the plugin.
