### ISSUE TITLE
[0.6] Add Russian language

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/saturn-theme#215]
{
  "poweredBy": "Разработано в",
  "classicVersion": "Обычная версия",
  "loadMore": "Загрузить ещё",
  "writtenBy": "Автор: ",
  "shares": "Поделиться",
  "sharesPlural": "Поделились",
  "sharesWithNumber": "Поделился: #number#",
  "sharesWithNumberPlural": "Поделились: #number#",
  "readingTime": "#number# мин.",
  "readingTimePlural": "#number# мин.",
  "next": "Далее",
  "loading": "Загрузка...",
  "share": "Поделиться",
  "copyLink": "Скопировать",
  "copiedLink": "Скопировано",
  "interestedPosts": "Вам также понравится...",
  "nextPosts": "Далее",
  "moreInCategory": "Ещё в категории #category#",
  "notifications": "Уведомления",
  "gdpr": "Настройки конфиденциальности",
  "comments": "Комментарии"
}

----
#cs: @SantosGuillamot
#supporter: @orballo

https://frontity.pipedrive.com/deal/681
Site pageviews: **(0.01)**
Extra group sites: **(0)**
Extra group pageviews: **(0)**
Development size: **(1)**
Blocking: **expected (x3)**
Environment: **integration is finishing (x10)**
Reusability potential: **marginal (x2)**
PRIORITY: **[0.6]**

**Comment by luisherranz** [comment]
Wow!! Awesome 😁
