### ISSUE TITLE
Remove GDPR "configuration" button

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#27]
![androidayuda.com__server=https___localhost_3000(Pixel 2).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46e99a9e318d8aad8ef0aa47a513f39b247918602c16b52e62d8eb3cab52683e303012f31209031ca3bacd44a5b63c70923c52a584314f76df2f0dbef8c040e554e964994597b3ee8e4fc3ec3a24e38bdc4c3b1d05188bf90f66a4c81e9c4aea59a31c0bf04c6b3aac23746e4d861f7d266a6225aaffd657848068a5ba113d1b.png)

The documentation is here:
https://help.quantcast.com/hc/en-us/articles/360003814853-Technical-Implementation-Guide

**Comment by rmartinezduque** [comment]
@luisherranz me puedes avisar cuando esté solucionado? Gracias! :)

**Comment by luisherranz** [comment]
It's solved in this PR (https://github.com/frontity/saturn-theme/pull/28) but it won't be ready until the new version is. So next Monday.

(BTW, try to use English here ☺️ )

**Comment by rmartinezduque** [comment]
Great, thanks Luis 👍🏻
