### ISSUE TITLE
Requesting page out of range

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#54]
If you visit this URL:
https://blog.frontity.com/category/business-marketing/
and swipe right, you can see it is trying to request an out of range url:
https://blog.frontity.com/?rest_route=/wp/v2/posts&_embed=true&categories=9&page=2&per_page=10

**Comment by orballo** [comment]
@luisherranz I can't reproduce this issue. Everything looks fine to me.

**Comment by luisherranz** [comment]
You're right, seems to be working now. I'll reopen if I see it again 👍
