### ISSUE TITLE
TagList doesn't render anything when the entity type is not 'post'

### ISSUE THREAD

**Issue by DAreRodz** [frontity/saturn-theme#58]
Related code [here](https://github.com/frontity/saturn-theme/blob/f9d2fe2d292687c0b589db9abc5b96019cccceea/src/pwa/components/Post/TagList.js#L47#L48).

**Comment by orballo** [comment]
@DAreRodz could you provide a link where this behaviour can be tested?

**Comment by DAreRodz** [comment]
Yeah, go to https://www.diariomotor.com/competicion/noticia/el-porsche-cayman-r-gt-asfalto-galo/ and scroll down to the end of the post.

**Comment by orballo** [comment]
@DAreRodz Thanks, so this wasn't a db setting after all.

**Comment by DAreRodz** [comment]
@orballo indeed, there is another open issue to solve that: https://github.com/frontity/saturn-theme/issues/59
