### ISSUE TITLE
[AMP] AMP markup missing or incorrect (Critical issue)

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#63]
Fix missing or invalid AMP markup on your page. AMP pages with missing required code or invalid AMP syntax may appear in Google search results without AMP-specific display features.

List of pages: https://drive.google.com/file/d/1O7b3GyuONyZqwgojKharjHpaQqRF2-DH/view?usp=sharing

**Please mention me once the issue is resolved so I can get back to the customer**

**Comment by orballo** [comment]
@Poliuk This issue has been solved but the costumer will have to update our plugin. @luisherranz should let you know when it's released.

**Comment by Poliuk** [comment]
@orballo We should check if the other issues (#60 #61 #62) are related. So we just release one version that fixes all the problems :) Thanks!
