### ISSUE TITLE
[AMP] Server error (5xx)

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#69]
The customer is saying that lots of pages are giving a error 5XX. And the number is increasing over the time. 

> Pages suffering the issue: https://drive.google.com/open?id=1y7On5TIre26shnX3kvUcpaEf8GrTTO6Q

**Please mention me once the issue has been solved so I can get back to the customer**

**Comment by orballo** [comment]
Fixed in https://github.com/frontity/saturn-theme/pull/65

**Comment by Poliuk** [comment]
@orballo Im running the search console validator and it is throwing an error saying it is still finding pages with the issue.
![Screen Shot 2018-08-06 at 17.49.23.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f56b7191a379e80c2f58415d4dbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5bf34ce14b5da5103167f43b.png)

This is the link to the page displayed in the alert: https://amp.wp-pwa.com/por-que-se-desato-la-guerra-civil-en-los-estados-unidos/?siteId=NhDkq2zHGK24Rx274&env=prod&dev=false&singleType=post&singleId=3452&initialUrl=https://sobrehistoria.com/por-que-se-desato-la-guerra-civil-en-los-estados-unidos/ Can you check if you see something extrange on it?  When I run the AMP validator it says the page is valid: https://validator.ampproject.org/#url=https%3A%2F%2Famp.wp-pwa.com%2Fpor-que-se-desato-la-guerra-civil-en-los-estados-unidos%2F%3FsiteId%3DNhDkq2zHGK24Rx274%26env%3Dprod%26dev%3Dfalse%26singleType%3Dpost%26singleId%3D3452%26initialUrl%3Dhttps%3A%2F%2Fsobrehistoria.com%2Fpor-que-se-desato-la-guerra-civil-en-los-estados-unidos%2F so I don't understand what's going on.

**Comment by orballo** [comment]
@Poliuk I guess it's a AMP cache problem? Everything looks fine to me in those links.

**Comment by Poliuk** [comment]
@orballo yep, I think the same, just wanted to confirm. Let's wait :)
