### ISSUE TITLE
[46] Support for WP post embeds

### ISSUE THREAD

**Issue by luisherranz** [frontity/saturn-theme#74]
Problem: The height of the wp-embed iframe is unknown until the iframe is rendered.

- [ ] PWA support
- [ ] AMP support

For PWA support, we can create a converter which executes this JS code that should change the iframe height properly:
https://gist.github.com/luisherranz/a8b0e4c3eba6f446e16fee736b8cf908

For AMP support, we need to investigate what the [wp-amp](https://github.com/Automattic/amp-wp) plugin is doing to change the height. Maybe we can install it and see what happens.

----

https://frontity.pipedrive.com/deal/13

Site pageviews: **(1.6M)**
Group sites: **(1M)**
Group pageviews: **(1.6M)**
Development size: **(5M)**
Blocking: **nice to have (x1)**
Environment: **production (x3)**
Reusability potential: **broad (x6)**
Case Study: **yes (x5)**
PRIORITY: **[46.08]**

**Comment by luisherranz** [comment]
After a bit of research I've found this PR in amp-wp from Weston:
https://github.com/Automattic/amp-wp/pull/914/files

It looks like amp-wp doesn't support wp-embed yet either.

He is suggesting to add this to WP core:
```js
/**
 * Add JS required for iframe to resize itself in AMP.
 *
 * @todo This should be incorporated into core.
 * @since ?.?
 */
function amp_add_post_embed_js() {
	?>
	<script>
	if ( /amp=1/.test( location.hash ) ) {
		window.parent.postMessage({
			sentinel: 'amp',
			type: 'embed-size',
			height: document.body.scrollHeight
		}, '*');
	}
	</script>
	<?php
}
add_action( 'embed_footer', 'amp_add_post_embed_js' );
```

Which is taking from here:
https://www.ampproject.org/docs/reference/components/amp-iframe#iframe-resizing

We could add that code to our plugin, then add `#amp=1` to the iframe src in our converter and render the wp-embed iframe like this:
```html
<amp-iframe width=300 height=300
    layout="responsive"
    sandbox="allow-scripts allow-same-origin"
    resizable
    src="https://wp-blog.com/post-one#amp=1">
  <div overflow tabindex=0 role=button aria-label="Read more">Read more!</div>
</amp-iframe>
```

Then we should take out the `amp_add_post_embed_js` function once it's merged to the core.

**Comment by SantosGuillamot** [comment]
We'll use the code without `amp=1`:
```js
		window.parent.postMessage({
			sentinel: 'amp',
			type: 'embed-size',
			height: document.body.scrollHeight
		}, '*');
	```

**Comment by luisherranz** [comment]
Once it's finished, we should remove `removeWpEmbeddedContent`:
https://github.com/frontity/saturn-theme/blob/dev-stable/src/shared/processors/low/removeWpEmbeddedContent.js

**Comment by SantosGuillamot** [comment]
#notify
