### ISSUE TITLE
[AMP] Content mismatch between AMP and canonical pages (Critical)

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#75]
Ensure that the AMP page and canonical page have the same content. AMP pages with content that doesn't match their canonical page may appear in Google Search results without AMP-specific display features.

**AMP URL:**
https://amp.herencia.net/evento/pregon-de-semana-santa/?siteId=uTJtb3FaGNZcNiyCb&env=prod&dev=false&singleType=post&singleId=31025&initialUrl=https://herencia.net/evento/pregon-de-semana-santa/

**Canonical URL:**	
https://herencia.net/evento/pregon-de-semana-santa/?mc_id=513

Child of https://github.com/frontity/wp-plugin/issues/11

**Comment by orballo** [comment]
This is a `custom post type` that is not in the Rest API, so we can't render it. Waiting for @luisherranz that will investigate if excluding it works with AMP.

**Comment by luisherranz** [comment]
Yes, I need to check if excludes is working with AMP but there's nothing else you can do here @orballo so I'll assign it to myself.
