### ISSUE TITLE
[AMP] Forbidden or incorrect HTML tag

### ISSUE THREAD

**Issue by Poliuk** [frontity/saturn-theme#86]
```
https://thewing.es/greg-monroe-raptors-aspiran-este/
https://thewing.es/jahlil-okafor-cobijo-anthony-davis/
https://thewing.es/cavs-rodney-hood-estancadas/
https://thewing.es/bazemore-batum-houston-rockets/
```

*Please tell me when the bug has been solved so I can get back with the customer*

**Comment by orballo** [comment]
I ran this sites against the `dev` branch and the content passes the AMP validator.  We just need to release the last changes in production.
